name: mi_card
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.1.2
  webview_flutter: 0.2.0


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
   - images/
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Cantarell
      fonts:
        - asset: fonts/Cantarell-Regular.ttf
        - asset: fonts/Cantarell-RegularItalic.ttf
        - asset: fonts/Cantarell-Bold.ttf
        - asset: fonts/Cantarell-BoldItalic.ttf
  